<?xml version="1.0" ?>
<robot name="uwb_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Define robot dimensions and properties -->
  <xacro:property name="base_length" value="0.15" />
  <xacro:property name="base_width" value="0.20" />
  <xacro:property name="base_height" value="0.05" />
  <xacro:property name="wheel_radius" value="0.05" />
  <xacro:property name="wheel_width" value="0.04" />

  <!-- Base Link (main body of the robot) -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
      <material name="blue">
        <color rgba="0 0 0.8 1" />
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="5.0" />
      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1" />
    </inertial>
  </link>

  <!-- LiDAR Link -->
  <link name="laser_link">
    <visual>
      <geometry>
        <cylinder radius="0.025" length="0.02" />
      </geometry>
      <material name="black">
        <color rgba="0 0 0 1" />
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.05" length="0.04" />
      </geometry>
    </collision>
    <inertial>
      <mass value="0.1" />
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001" />
    </inertial>
  </link>

  <!-- Joint connecting base_link to laser_link -->
  <joint name="laser_joint" type="fixed">
    <parent link="base_link" />
    <child link="laser_link" />
    <!-- Position LiDAR at the front-top of the robot -->
    <origin xyz="0 0 ${base_height/2 + 0.1}" rpy="0 0 0" />
  </joint>

  <!-- IMU Link -->
  <link name="imu_link">
    <visual>
      <geometry>
        <box size="0.03 0.03 0.01" />
      </geometry>
      <material name="red">
        <color rgba="1 0 0 1" />
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.03 0.03 0.01" />
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01" />
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001" />
    </inertial>
  </link>

  <!-- Joint connecting base_link to imu_link -->
  <joint name="imu_joint" type="fixed">
    <parent link="base_link" />
    <child link="imu_link" />
    <!-- Position IMU at the center-top of the robot -->
    <origin xyz="0 0 ${base_height/2 + 0.005}" rpy="0 0 0" />
  </joint>

  <!-- UWB Link -->
  <link name="uwb_link">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.01" />
      </geometry>
      <material name="green">
        <color rgba="0 1 0 1" />
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.05 0.01" />
      </geometry>
    </collision>
    <inertial>
      <mass value="0.05" />
      <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001" />
    </inertial>
  </link>

  <!-- Joint connecting base_link to uwb_link -->
  <joint name="uwb_joint" type="fixed">
    <parent link="base_link" />
    <child link="uwb_link" />
    <!-- Position UWB at the back-top of the robot -->
    <origin xyz="${-base_length/4} 0 ${base_height/2 + 0.005}" rpy="0 0 0" />
  </joint>

</robot>
