slam_toolbox:
  ros__parameters:
    # Enable simulation time
    use_sim_time: true

    # Frame IDs
    odom_frame: odom
    base_frame: base_link
    map_frame: map

    # Topics
    scan_topic: /scan
    odom_topic: /odom

    # Mode
    mode: mapping # Use 'mapping' for building a new map (default for async)

    # Transform tolerance
    transform_tolerance: 0.5 # Allow 0.5 seconds tolerance for TF lookups

    # LiDAR settings
    min_laser_range: 0.2 # Adjust to your LiDAR's min range (e.g., 0.1 meters)
    max_laser_range: 12.0 # Adjust to your LiDAR's max range (e.g., 20 meters)
    scan_buffer_size: 100 # Number of scans to buffer
    scan_buffer_maximum_scan_distance: 20.0 # Max distance for scans in buffer

    # Mapping update settings
    minimum_travel_distance: 0.0 # Minimum distance (meters) to travel before updating map
    minimum_travel_heading: 0.0 # Minimum heading change (radians) before updating map

    # Other settings
    use_map_saver: true # Enable map saving
    map_update_interval: 5.0 # How often to update the map (seconds)
